AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  LessURL-Serverless

  Java 21 & SnapStart based URL Shortener Service

Globals:
  Function:
    Timeout: 20
    MemorySize: 1024
    Runtime: java21
    Architectures:
      - x86_64
    AutoPublishAlias: live
    Environment:
      Variables:
        URLS_TABLE: !Ref UrlsTable
        CLICKS_TABLE: !Ref ClicksTable

Resources:
  # API Gateway
  UrlShortenerApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Cors:
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'Content-Type'"
        AllowOrigin: "'*'"

  # DynamoDB Tables
  UrlsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: urls
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: shortId
          AttributeType: S
      KeySchema:
        - AttributeName: shortId
          KeyType: HASH

  ClicksTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: clicks
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: shortId
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: S
      KeySchema:
        - AttributeName: shortId
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE

  # Lambda Functions
  # 1. 단축 생성: 쓰기(PutItem)만 가능
  ShortenFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: LessUrlFunction/build/libs/LessUrlFunction-all.jar
      Handler: lessurl.ShortenHandler::handleRequest
      SnapStart:
        ApplyOn: PublishedVersions
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref UrlShortenerApi
            Path: /shorten
            Method: POST
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
              Resource: !GetAtt UrlsTable.Arn

  # 2. 리다이렉트: URL조회(Get), 수정(Update) / 클릭기록(Put)
  RedirectFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: LessUrlFunction/build/libs/LessUrlFunction-all.jar
      Handler: lessurl.RedirectHandler::handleRequest
      SnapStart:
        ApplyOn: PublishedVersions
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref UrlShortenerApi
            Path: /{shortId}
            Method: GET
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:UpdateItem
              Resource: !GetAtt UrlsTable.Arn
            - Effect: Allow
              Action:
                - dynamodb:PutItem
              Resource: !GetAtt ClicksTable.Arn

  # 3. 통계: URL조회(Get) / 클릭조회(Query)
  StatsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: LessUrlFunction/build/libs/LessUrlFunction-all.jar
      Handler: lessurl.StatsHandler::handleRequest
      SnapStart:
        ApplyOn: PublishedVersions
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref UrlShortenerApi
            Path: /stats/{shortId}
            Method: GET
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
              Resource: !GetAtt UrlsTable.Arn
            - Effect: Allow
              Action:
                - dynamodb:Query
              Resource: !GetAtt ClicksTable.Arn

  # Cloud Watch 알람 설정
  MonitoringTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: "LessUrl-Alarms"
      Subscription:
        - Protocol: email
          Endpoint: "lold2424@gmail.com"

  # Lambda Errors: 에러 > 10/분 일 때 알람 발송
  LambdaErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${AWS::StackName}-lambda-errors"
      AlarmDescription: "Lambda Errors > 10/min"
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 1
      Threshold: 10
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref ShortenFunction
      AlarmActions:
        - !Ref MonitoringTopic

  # Lambda Duration: 실행시간 > 3초 (3000ms) 일 때 알람 발송
  LambdaDurationAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${AWS::StackName}-lambda-duration"
      AlarmDescription: "Lambda Duration > 3s"
      MetricName: Duration
      Namespace: AWS/Lambda
      Statistic: Average
      Period: 60
      EvaluationPeriods: 1
      Threshold: 3000
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref ShortenFunction
      AlarmActions:
        - !Ref MonitoringTopic

  # API Gateway 5XX: 서버 에러 > 5/분 일 때 알람 발송
  ApiGateway5xxAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${AWS::StackName}-api-5xx"
      AlarmDescription: "API 5XX > 5/min"
      MetricName: 5XXError
      Namespace: AWS/ApiGateway
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 1
      Threshold: 5
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: ApiName
          Value: !Ref UrlShortenerApi
      AlarmActions:
        - !Ref MonitoringTopic

  # API Gateway 4XX: 클라이언트 에러 > 50/분 일 때 알람 발송
  ApiGateway4xxAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${AWS::StackName}-api-4xx"
      AlarmDescription: "API 4XX > 50/min"
      MetricName: 4XXError
      Namespace: AWS/ApiGateway
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 1
      Threshold: 50
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: ApiName
          Value: !Ref UrlShortenerApi
      AlarmActions:
        - !Ref MonitoringTopic

  # DynamoDB: 읽기 스로틀링 발생 시 알람 발송
  DynamoDbThrottleAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${AWS::StackName}-ddb-throttles"
      AlarmDescription: "DynamoDB Throttled Events"
      Namespace: AWS/DynamoDB
      MetricName: ReadThrottleEvents
      Dimensions:
        - Name: TableName
          Value: !Ref UrlsTable
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 1
      Threshold: 0
      ComparisonOperator: GreaterThanThreshold
      AlarmActions:
        - !Ref MonitoringTopic

Outputs:
  ApiEndpoint:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${UrlShortenerApi}.execute-api.${AWS::Region}.amazonaws.com/prod"

  UrlsTableName:
    Description: "URLs DynamoDB Table"
    Value: !Ref UrlsTable

  ClicksTableName:
    Description: "Clicks DynamoDB Table"
    Value: !Ref ClicksTable
