### URL 단축 확인
POST https://qiariagfh0.execute-api.ap-northeast-2.amazonaws.com/prod/shorten
Content-Type: application/json

{
  "url": "https://github.com/lold2424",
  "title": "IntelliJ HTTP Client Search"
}

### URL 리다이렉트 확인
GET https://qiariagfh0.execute-api.ap-northeast-2.amazonaws.com/prod/737db8a5
