### URL 단축 확인
POST https://qiariagfh0.execute-api.ap-northeast-2.amazonaws.com/prod/shorten
Content-Type: application/json

{
  "url": "https://www.google.com",
  "title": "Example for Stats Test"
}

> {%
    // 응답이 성공했을 때만 실행
    if (response.status === 200) {
        // 1. shortId 변수 저장
        client.global.set("shortId", response.body.shortId);

        // 2. 로그 출력 (디버깅용)
        client.log("Saved shortId: " + response.body.shortId);
    }
%}

### URL 리다이렉트 확인
GET https://qiariagfh0.execute-api.ap-northeast-2.amazonaws.com/prod/{{shortId}}

### URL 통계 확인
GET https://qiariagfh0.execute-api.ap-northeast-2.amazonaws.com/prod/stats/{{shortId}}
Accept: application/json
